#! /bin/sh

pgrep -x sxhkd > /dev/null || sxhkd &
  
bspc monitor -d          
#bspc monitor -d I II III IV V VI VII VIII

#bspc config border_width         3
#bspc config window_gap           50

#bspc config normal_border_color \#474747
#bspc config focused_border_color \#474747

bspc config split_ratio          .50
bspc config borderless_monocle   true
bspc config gapless_monocle      true

bspc rule -a Gimp desktop='^8' state=floating follow=on
bspc rule -a Chromium desktop='^2'
bspc rule -a mplayer2 state=floating
bspc rule -a Kupfer.py focus=on
bspc rule -a Screenkey manage=off
bspc rule -a Spotify desktop='^2'
bspc rule -a Pokerstars state=floating
bspc rule -a PokerStarsBr.exe
bspc rule -a Steam desktop='^3' state=floating
wal -o ~/.config/wal/done.sh --theme base16-tomorrow-night
xset s off -dpms
~/.config/feh/tile.sh 000000
#feh --bg-scale ~/.fehbg/wall.png
wal -i ~/.fehbg/purple.jpg
xsetroot -cursor_name left_ptr &
xrandr --output HDMI-0 --mode 1920x1080 --rate 74.97 &
bspc config focus_follows_pointer true &
picom --experimental-backends &
dunst &
sudo mount -t ntfs-3g /dev/nvme0n1p3 /mnt/windows
#sh .config/polybar/launch.sh
setxkbmap -option grp:alt_shift_toggle us,ru &
#xwallpaper --zoom .config/walls/coast.png &


# Start polybar and other things based on DPI
# Get the host width
HOST_WIDTH=$(bspc query -T -m | jq '.rectangle.width')

CURSOR_THEME=${XCURSOR_THEME:-breeze_cursors}

# If the DPI is not set, set it to 96 by default
if [ -z "$(xrdb -query | grep dpi)" ]; then
  X_DPI=96
fi

# Determine the DPI based on screen width
if [ "$HOST_WIDTH" -eq "1920" ]; then
  X_DPI=96
fi

if [ "$HOST_WIDTH" -eq "3840" ]; then
  X_DPI=192
fi

# Reposition the desktop background
~/.fehbg &

# If the DPI needs to be changed, change it
if [ "$X_DPI" ]; then
  echo "Xft.dpi:$X_DPI" | xrdb -merge

  # Change the X cursor size as well
  # NOTE: For full effect, this needs to be used in combination with XCURSOR_SIZE.
  # NOTE: ($X_DPI / 6) here means that 4k will use cursor size 32, so it will appear
  #       about half the size of the 1080p cursor. If this is not what you want, use
  #       cursor size 64 instead.
  xsetroot -xcf "/usr/share/icons/$CURSOR_THEME/cursors/left_ptr" "$(($X_DPI / 6))"
fi

sh .config/polybar/launch.sh
